name = "cache-clear-webhook"
main = "index.js"
no_bundle = true
compatibility_date = "2022-11-12"
workers_dev = false
route = { pattern = "cache.erisa.dev/*", zone_name = "erisa.dev" }
account_id = "ece1d09b06af2ced51407c97505ea0cc"
